// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWJA-45rFTrvzLgfBUzUgT6d8qjbcHNI',
    appId: '1:523281733713:web:964a336fa54a3fe0b34070',
    messagingSenderId: '523281733713',
    projectId: 'jyantoddjobs',
    authDomain: 'jyantoddjobs.firebaseapp.com',
    storageBucket: 'jyantoddjobs.appspot.com',
    measurementId: 'G-HTE16DE9D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwlVXpbht9DLt85NKQAWbdCQbt0uFKHkA',
    appId: '1:523281733713:android:8febb92326dd6e43b34070',
    messagingSenderId: '523281733713',
    projectId: 'jyantoddjobs',
    storageBucket: 'jyantoddjobs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4zNb4KhBSi-75KVcrsxaTGfvPWlCKGQY',
    appId: '1:523281733713:ios:bf77dba175b39bfdb34070',
    messagingSenderId: '523281733713',
    projectId: 'jyantoddjobs',
    storageBucket: 'jyantoddjobs.appspot.com',
    iosBundleId: 'com.example.oddJobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4zNb4KhBSi-75KVcrsxaTGfvPWlCKGQY',
    appId: '1:523281733713:ios:bf77dba175b39bfdb34070',
    messagingSenderId: '523281733713',
    projectId: 'jyantoddjobs',
    storageBucket: 'jyantoddjobs.appspot.com',
    iosBundleId: 'com.example.oddJobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxWJA-45rFTrvzLgfBUzUgT6d8qjbcHNI',
    appId: '1:523281733713:web:be1ed973deedaf3eb34070',
    messagingSenderId: '523281733713',
    projectId: 'jyantoddjobs',
    authDomain: 'jyantoddjobs.firebaseapp.com',
    storageBucket: 'jyantoddjobs.appspot.com',
    measurementId: 'G-27SH39D1JW',
  );
}
